apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcriverfest
  labels:
    tier: frontend
    app: kcriverfest
spec:
  selector:
    matchLabels:
      app: kcriverfest
  replicas: 1
  template:
    metadata:
      labels:
        app: kcriverfest
    spec:
      containers:
      - name: kcriverfest
        image: kcriverfest
