apiVersion: v1
kind: Service
metadata:
  name: kcriverfest
  labels:
    tier: frontend
    app: kcriverfest
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: kcriverfest
